# windows constants
WINDOW_HEIGHT = 500                                     
WINDOW_WIDTH = 800                                      
WINDOW_SIZE = f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}"
WINDOW_TITLE = "Ticket Booking"         
WINDOW_TRANSPARENCY = "1"                               

# default frame
DEFAULT_FRAME_BACK_HEIGHT_PERCENT = 0.1                 
DEFAULT_FRAME_BACK_HEIGHT = DEFAULT_FRAME_BACK_HEIGHT_PERCENT * WINDOW_HEIGHT
DEFAULT_FRAME_DATA_HEIGHT = (1-DEFAULT_FRAME_BACK_HEIGHT_PERCENT) * WINDOW_HEIGHT
DEFAULT_BACK_IMAGE_WIDTH_PERCENT = 0.05
DEFAULT_BACK_IMAGE_WIDTH = int (DEFAULT_BACK_IMAGE_WIDTH_PERCENT * WINDOW_WIDTH )
DEFAULT_BACK_IMAGE_X_POS = 20
DEFAULT_BACK_IMAGE_Y_POS = 10


# main menu constants
MM_BUTTONS_DICT = {1 : "Login", 2 : " Ticket Booking ", 3 : "Save session", 4 : "Load session", 5 : "Report", 6 : "Exit"}
MM_BUTTON_WIDTH_PERCENT = 0.05                         
MM_BUTTON_Y_PADDING_PERCENT = 0.02                   
MM_BUTTON_GRID_PADDING_PERCENT = 0.02                   
MM_BUTTON_WIDTH = int (WINDOW_WIDTH * MM_BUTTON_WIDTH_PERCENT)
MM_BUTTON_Y_PADDING = int (WINDOW_HEIGHT * MM_BUTTON_Y_PADDING_PERCENT )
MM_BUTTON_GRID_PADDING = WINDOW_HEIGHT * MM_BUTTON_GRID_PADDING_PERCENT
